In [40]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Create a toy dataset
data = {
    'income': [30, 50, 20, 70, 90, 40, 60, 80, 25, 35],
    'credit_score': [600, 650, 500, 700, 750, 620, 670, 720, 580, 610],
    'default': [1, 0, 1, 0, 0, 1, 0, 0, 1, 1]
}

df = pd.DataFrame(data)

# Define predictors and target
X = df[['income', 'credit_score']]
y = df['default']

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fit a logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Show test data and predictions
test_results = X_test.copy()
test_results['actual'] = y_test
test_results['predicted'] = y_pred

print("\nTest Results:")
print(test_results)


Accuracy: 1.0

Test Results:
   income  credit_score  actual  predicted
8      25           580       1          1
1      50           650       0          0
5      40           620       1          1


In [41]:
df

income  credit_score  default
0      30           600        1
1      50           650        0
2      20           500        1
3      70           700        0
4      90           750        0
5      40           620        1
6      60           670        0
7      80           720        0
8      25           580        1
9      35           610        1

In [42]:
model.coef_

array([[-0.07065699, -0.16898922]])

In [43]:
model.intercept_

array([111.56891517])

In [44]:
test_results[['income','credit_score']].values

array([[ 25, 580],
       [ 50, 650],
       [ 40, 620]])

In [45]:
import numpy as np

def predict_logistic_regression(coefficients, intercept, features, scaler=None):
    # Apply scaling if scaler is provided
    if scaler is not None:
        features = scaler.transform(features)

    # Compute the linear combination: z = intercept + sum(coeff * feature)
    z = np.dot(features, coefficients) + intercept

    # Apply the sigmoid function to compute probabilities
    probabilities = 1 / (1 + np.exp(-z))

    # Convert probabilities to class predictions (threshold at 0.5)
    predictions = (probabilities >= 0.5).astype(int)

    return probabilities, predictions

In [46]:


# Call the function (no scaling in this example)
probabilities, predictions = predict_logistic_regression(model.coef_.flatten(), model.intercept_[0], test_results[['income','credit_score']].values)

# Print results
for i, (prob, pred) in enumerate(zip(probabilities, predictions)):
    print(f"Sample {i+1}: Probability = {prob:.4f}, Predicted Class = {pred}")

Sample 1: Probability = 1.0000, Predicted Class = 1
Sample 2: Probability = 0.1410, Predicted Class = 0
Sample 3: Probability = 0.9815, Predicted Class = 1


In [62]:
np.round(model.predict_proba(X_test),5)[:,1]

array([0.99999, 0.14101, 0.98146])

In [63]:
model.coef_

array([[-0.07065699, -0.16898922]])

In [64]:
1/(1+np.exp(-(111.5689 -0.07065699*25 -0.16898922*580)))

0.9999924104271004

In [65]:
1/(1+np.exp(-(111.5689 -0.07065699*50 -0.16898922*650)))

0.14100805843407024

In [66]:
1/(1+np.exp(-(111.5689 -0.07065699*40 -0.16898922*620)))

0.9814635170331816