In [7]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder

# Dataset: Feature columns and target
data = {
    "Age": ["young", "young", "middle_aged", "senior", "senior", "senior", "middle_aged", "young", "young", "senior"],
    "Income": ["medium", "low", "high", "medium", "medium", "low", "low", "medium", "high", "high"],
    "Student": ["no", "yes", "no", "no", "no", "yes", "yes", "no", "yes", "yes"],
    "Credit_Rating": ["fair", "excellent", "fair", "fair", "excellent", "excellent", "fair", "excellent", "fair", "fair"],
    "Buy_Car": ["no", "yes", "yes", "no", "no", "yes", "yes", "no", "yes", "no"]
}

# Convert dataset to a pandas DataFrame
df = pd.DataFrame(data)

# Separate features (X) and target (y)
X = df[["Age", "Income", "Student", "Credit_Rating"]]
y = df["Buy_Car"]

# Encode categorical features into numeric form
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)
print(X_encoded)

# Encode the target
y_encoded = np.where(y == "yes", 1, 0)

# Train a Categorical Naive Bayes model
model = CategoricalNB()
model.fit(X_encoded, y_encoded)

test_instance = pd.DataFrame(
    [["young", "medium", "no", "fair"]],
    columns=["Age", "Income", "Student", "Credit_Rating"]
)

# Encode the test instance
test_encoded = encoder.transform(test_instance)

# Make predictions
predicted_class = model.predict(test_encoded)
predicted_probabilities = model.predict_proba(test_encoded)

# Make predictions
predicted_class = model.predict(test_encoded)
predicted_probabilities = model.predict_proba(test_encoded)

# Print results
print(f"Test Instance: {test_instance}")
print(f"Predicted Class: {'yes' if predicted_class[0] == 1 else 'no'}")
print(f"Predicted Probabilities: {predicted_probabilities}")


[[2. 2. 0. 1.]
 [2. 1. 1. 0.]
 [0. 0. 0. 1.]
 [1. 2. 0. 1.]
 [1. 2. 0. 0.]
 [1. 1. 1. 0.]
 [0. 1. 1. 1.]
 [2. 2. 0. 0.]
 [2. 0. 1. 1.]
 [1. 0. 1. 1.]]
Test Instance:      Age  Income Student Credit_Rating
0  young  medium      no          fair
Predicted Class: no
Predicted Probabilities: [[0.92592593 0.07407407]]
